package co.uniquindio.ingesis.dto.FeedbackResource;

import jakarta.validation.constraints.NotBlank;

/**
 * Data Transfer Object (DTO) representing feedback provided by a teacher for a
 * program.
 *
 * @param id        the unique identifier of the feedback (auto-generated by the
 *                  database)
 * @param comment   the teacher's comment (must not be blank)
 * @param programId the ID of the program to which the feedback belongs
 * @param teacherId the ID of the teacher who provided the feedback
 */
public record FeedbackDto(

        Integer id,

        @NotBlank String comment,

        Long programId,

        Integer teacherId

) {
}
