services:
  postgres:
    image: postgres
    container_name: javaclassroom
    restart: always
    environment:
      POSTGRES_USER: java_classroom
      POSTGRES_PASSWORD: java_classroom
      POSTGRES_DB: java_classroom
    ports:
      - "5432:5432"
    volumes:
      - java_class_data:/var/lib/postgresql/data



volumes:
  java_class_data:
