networks:
  classroom_red:
    ipam:
      config:
        - subnet: 192.171.0.0/24

services:
  postgres-quarkus:
    image: postgres
    container_name: classroom_postgres
    restart: always
    environment:
      POSTGRES_USER: classroom
      POSTGRES_PASSWORD: classroom2025
      POSTGRES_DB: classroom_db
    networks:
      classroom_red:
        ipv4_address: 192.171.0.30
    ports:
      - "5432:5432"
    volumes:
      - quarkus_pg_data:/var/lib/postgresql/data

  quarkus-app:
    build:
      context: ./../../../
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus_container
    depends_on:
      - postgres-quarkus
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: classroom
      QUARKUS_DATASOURCE_PASSWORD: classroom2025
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://classroom_postgres:5432/classroom_db
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
      QUARKUS_DATASOURCE_JDBC_DRIVER: org.postgresql.Driver
    networks:
      classroom_red:
        ipv4_address: 192.171.0.20
    ports:
      - "8081:8080"

volumes:
  quarkus_pg_data:
