networks:
  cacique_red:
    ipam:
      config:
        - subnet: 192.180.0.0/24

services:
  postgres:
    image: postgres
    container_name: javaclassroom
    restart: always
    environment:
      POSTGRES_USER: java_classroom
      POSTGRES_PASSWORD: java_classroom
      POSTGRES_DB: java_classroom
    networks:
      cacique_red:
        ipv4_address: 192.180.0.30
    ports:
      - "5000:5000"
    volumes:
      - java_class_data:/var/lib/postgresql/data



volumes:
  java_class_data:
